### ISSUE TITLE
Unable to add the project to gradle file

### ISSUE THREAD

**Issue by rwendelboe** [agrawalsuneet/LoadersPack-Android#26]
I am getting an error when I'm trying to add your project to my gradle file. This is the error I get

Android resource compilation failed
Output:
android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:988: error: duplicate value for resource 'attr/startAngle' with config ''.
android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:988: error: resource previously defined here.

**Comment by agrawalsuneet** [comment]
@rwendelboe please try to clean and build again. If you still face the issue, please use the aar file from [releases](https://github.com/agrawalsuneet/LoadersPack-Android/releases).

Although I tried the same dependency ([v1.1](https://github.com/agrawalsuneet/LoadersPack-Android/releases/tag/v1.1)) in three different projects and its working fine still, use the local aar file if you face the issue again.

**Comment by agrawalsuneet** [comment]
@rwendelboe were you able to add the dependency into your project successfully or still facing an issue?

**Comment by agrawalsuneet** [comment]
Did you try to add the aar file into your project and use it?

**Comment by agrawalsuneet** [comment]
Closing this issue as this is completely outdated now. Open a new one if you still facing the issue.
