### ISSUE TITLE
noOfRipples reduces to 1 after visible

### ISSUE THREAD

**Issue by alihusseinalissa** [agrawalsuneet/LoadersPack-Android#29]
When I use MultipleRippleLoader with any number of ripples, and set its visibility to "INVISIBLE", and then set it to "VISIBLE" from code, the number of ripples reduces to 1, even if I tried to hide and unhide its parent.

XML code:

<com.agrawalsuneet.loaderspack.loaders.MultipleRippleLoader
                android:id="@+id/ripple_layout"
                android:layout_centerInParent="true"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:multipleripple_animDuration="6000"
                app:multipleripple_circleColor="@color/colorPrimary"
                app:multipleripple_circleInitialRadius="50dp"
                app:multipleripple_fromAlpha="0.8"
                app:multipleripple_interpolator="@android:anim/decelerate_interpolator"
                app:multipleripple_noOfRipples="3"
                app:multipleripple_toAplha="0" />

**Comment by agrawalsuneet** [comment]
fixed in https://github.com/agrawalsuneet/LoadersPack-Android/pull/30.
will be releasing it soon.

**Comment by alihusseinalissa** [comment]
> @alihusseinalissa fixed in #30.
> will be releasing it soon.

**Comment by alihusseinalissa** [comment]
OK, I'll be waiting.
Accidentally closed and reopened.

**Comment by agrawalsuneet** [comment]
@alihusseinalissa v1.2.1 is live now.

**Comment by alihusseinalissa** [comment]
Yes, it's now working perfectly. Thank you.
