### ISSUE TITLE
Animation issue when view is originally visibility:gone

### ISSUE THREAD

**Issue by Noam-Modai** [agrawalsuneet/LoadersPack-Android#32]
I am using CurvesLoader.
if the xml view is android:visibility="gone"
when programmatically switched to visible, the animation looks like there is a measurement problem.

**Comment by droiddevps** [comment]
Same problem. Any solution yet?

**Comment by agrawalsuneet** [comment]
@Noam-Modai @droiddevps I am really sorry I missed this issue as there was no notification for the same.
Will check an update soon.

**Comment by agrawalsuneet** [comment]
fixed the issue https://github.com/agrawalsuneet/LoadersPack-Android/pull/33
Will revert unwanted changes and release it soon.

**Comment by agrawalsuneet** [comment]
@Noam-Modai @droiddevps I have fixed the issue. Can you please use the latest version (1.2.2) and verify?
Also, if that works fine, can you close this issue?

**Comment by agrawalsuneet** [comment]
Closing this issue as this is fixed and verified.
